export default {
  "gallery-01": "Vyčištěný interiér vozu s panoramatickou střechou",
  "gallery-02": "Vyčištěné dveřní výplně a čalounění",
  "gallery-03": "Vyčištěná palubní deska a interiér vozu",
  "gallery-04": "Vyčištěné sedačky autobusu",
  "gallery-05": "Vyčištěné zadní sedačky luxusního vozu",
  "gallery-06": "Vyčištěné sedačky zájezdového autobusu",
  "gallery-07": "Čištění kabiny kamionu – průběh",
  "gallery-08": "Hloubkové čištění kožené sedačky",
  "gallery-09": "Čištění volantu a palubní desky",
  "gallery-10": "Vyčištěné sedačky linkového autobusu",
  "gallery-11": "Čištění prostoru řidiče autobusu",
  "gallery-12": "Vyčištěný interiér vozu",
  "gallery-13": "Interiér vozu před čištěním",
  "gallery-14": "Čištění kožené sedačky – průběh",
  "gallery-15": "Hloubkové čištění sedačky – průběh",
  "gallery-16": "Vyčištěné zadní sedačky a loketní opěrka",
  "gallery-17": "Vyčištěný interiér vozu Alfa Romeo",
  "gallery-18": "Vyčištěný sportovní interiér vozu",
};
